# This Action is responsible for deploying the default Hydrogen template to various runtimes as a CI step.
# This helps us detect when we've made a change that is potentially incompatible on an environment.
name: Deployments

on:
  workflow_dispatch:
  push:
    branches: ['v1.x-2022-07']

concurrency:
  group: deployments-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy_cloudflare:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shopify' }}
    name: Deploy to Cloudflare Workers
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build Hydrogen
        run: yarn workspace @shopify/hydrogen build

      - name: Make updates for Cloudflare Workers runtime
        working-directory: ./examples/template-hydrogen-default
        run: |
          cp ../../.github/deployments/cloudflare/* .
          yarn add @cloudflare/kv-asset-handler

      - name: Build for workers
        working-directory: ./examples/template-hydrogen-default
        run: |
          yarn build:client
          yarn cross-env WORKER=true vite build --outDir dist/worker --ssr worker

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.DEPLOYMENT_CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.DEPLOYMENT_CF_API_TOKEN }}
          workingDirectory: ./examples/template-hydrogen-default

      - name: Run health check
        run: |
          yarn ts-node scripts/health-check.ts https://template-default.hydrogen-devs.workers.dev/

  deploy_oxygen:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shopify' }}
    name: Deploy to Oxygen
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build Hydrogen
        run: yarn workspace @shopify/hydrogen build

      - name: Generate deployment ID
        id: deployment-id
        working-directory: ./examples/template-hydrogen-default
        run: |
          yarn add ulid
          echo "::set-output name=ID::$(LC_ALL=C </dev/urandom tr -dc "0123456789abcdefghjkmnpqrstvwxyz" | head -c 9)"

      - name: Set asset base URL
        shell: bash
        run: echo "::set-output name=URL::https://cdn.shopify.com/oxygen/55145660472/9863224/${{ steps.deployment-id.outputs.ID }}/"
        id: base-url

      - name: Production build
        id: storefront-build
        working-directory: ./examples/template-hydrogen-default
        run: |
          HYDROGEN_ASSET_BASE_URL=${{ steps.base-url.outputs.URL }} yarn build:client
          HYDROGEN_ASSET_BASE_URL=${{ steps.base-url.outputs.URL }} yarn build:worker

      - name: Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v2
        with:
          path: ./examples/template-hydrogen-default
          deployment_id: ${{ steps.deployment-id.outputs.ID }}
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
          # Hardcode message and timestamp if manual dispatch
          commit_message: ${{ github.event.head_commit.message || 'Manual deployment' }}
          commit_timestamp: ${{ github.event.head_commit.timestamp || github.event.repository.updated_at }}

      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}

      - name: Run health check
        run: |
          yarn ts-node scripts/health-check.ts ${{ steps.deploy.outputs.url }}
