# This Action is responsible for deploying the default Hydrogen template to various runtimes as a CI step.
# This helps us detect when we've made a change that is potentially incompatible on an environment.
name: Deployments

on:
  workflow_dispatch:
  push:
    branches: ['v1.x-2022-07']

concurrency:
  group: deployments-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy_cloudflare:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shopify' }}
    name: Deploy to Cloudflare Workers
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build Hydrogen
        run: yarn workspace @shopify/hydrogen build

      - name: Make updates for Cloudflare Workers runtime
        working-directory: ./examples/template-hydrogen-default
        run: |
          cp ../../.github/deployments/cloudflare/* .
          yarn add @cloudflare/kv-asset-handler

      - name: Build for workers
        working-directory: ./examples/template-hydrogen-default
        run: |
          yarn build:client
          yarn cross-env WORKER=true vite build --outDir dist/worker --ssr worker

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.DEPLOYMENT_CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.DEPLOYMENT_CF_API_TOKEN }}
          workingDirectory: ./examples/template-hydrogen-default
