name: Publish to Stackblitz

on:
  # Note: the `released` event does not currently work because
  # a bot is the creator of the release. Run this manually instead.
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish latest release to Stackblitz
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'v1.x-2022-07'
      - run: |
          mv templates/demo-store-ts/_gitignore templates/demo-store-ts/.gitignore
          mv templates/demo-store-js/_gitignore templates/demo-store-js/.gitignore
          mv templates/hello-world-ts/_gitignore templates/hello-world-ts/.gitignore
          mv templates/hello-world-js/_gitignore templates/hello-world-js/.gitignore
      - run: |
          sed -i.bak 's/cross-env LOCAL_DEV=true //' templates/demo-store-ts/package.json
          sed -i.bak 's/cross-env LOCAL_DEV=true //' templates/demo-store-js/package.json
          sed -i.bak 's/cross-env LOCAL_DEV=true //' templates/hello-world-ts/package.json
          sed -i.bak 's/cross-env LOCAL_DEV=true //' templates/hello-world-js/package.json
      - run: |
          git show-ref
          git config user.email "hydrogen@shopify.com"
          git config user.name "Hydrogen Bot"
          git commit -am "Update templates on Stackblitz branch"
          git push origin HEAD:stackblitz --force
