name: Publish to Stackblitz

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish latest release to Stackblitz
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Rename gitignore
        run: |
          mv packages/dev/_gitignore packages/dev/.gitignore
      - name: Push to stackblitz branch
        run: |
          git config user.email "hydrogen@shopify.com"
          git config user.name "Hydrogen Bot"
          git commit -am "Update Stackblitz branch"
          git push origin stackblitz --force

